## Part 1: Creating a Book Store Dataset

In this section, I created a small dataset representing book sales in a bookstore.

The dataset includes information such as book title, genre, number of copies sold, and price.  
This kind of data can help understand which types of books perform better.

The dataset contains 5 columns and 15 rows, along with custom index labels.

In [31]:
import pandas as pd

data = {
    "Book_Title": [
        "We Were Liers", "Deep Space", "Love Again", "Python Basics", "Silent Night",
        "Fast Mind", "Ocean Life", "Broken Path", "Data 101", "Sky High",
        "Dark World", "AI Intro", "Final Step", "Dream Catcher", "Code Master"
    ],

    "Genre": [
        "Fiction", "Sci-Fi", "Romance", "Education", "Mystery",
        "Self-Help", "Nature", "Drama", "Education", "Adventure",
        "Fantasy", "Education", "Drama", "Romance", "Technology"
    ],

    "Copies_Sold": [
        120, 85, 150, 200, 95,
        130, 75, 110, 180, 90,
        140, 210, 100, 160, 170
    ],

    "Price": [
        15, 18, 12, 25, 17,
        14, 16, 13, 22, 19,
        20, 24, 15, 12, 27
    ],

    "Total_Sales": [
        1800, 1530, 1800, 5000, 1615,
        1820, 1200, 1430, 3960, 1710,
        2800, 5040, 1500, 1920, 4590
    ]
}

index_labels = [
    "B1", "B2", "B3", "B4", "B5",
    "B6", "B7", "B8", "B9", "B10",
    "B11", "B12", "B13", "B14", "B15"
]

df = pd.DataFrame(data, index=index_labels)

df

        Book_Title       Genre  Copies_Sold  Price  Total_Sales
B1   We Were Liers     Fiction          120     15         1800
B2      Deep Space      Sci-Fi           85     18         1530
B3      Love Again     Romance          150     12         1800
B4   Python Basics   Education          200     25         5000
B5    Silent Night     Mystery           95     17         1615
B6       Fast Mind   Self-Help          130     14         1820
B7      Ocean Life      Nature           75     16         1200
B8     Broken Path       Drama          110     13         1430
B9        Data 101   Education          180     22         3960
B10       Sky High   Adventure           90     19         1710
B11     Dark World     Fantasy          140     20         2800
B12       AI Intro   Education          210     24         5040
B13     Final Step       Drama          100     15         1500
B14  Dream Catcher     Romance          160     12         1920
B15    Code Master  Technology          170     27         4590

### Observation

Each row represents a book and its sales record.  
The custom index (B1–B15) helps in identifying each entry easily.

In [32]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train (2).csv

## Part 2: Titanic Dataset Analysis
In this part, I worked with the Titanic dataset to explore passenger information and understand what factors affected survival.

In [33]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Initial Exploration

First, I explored the dataset to understand its structure, data types, and summary statistics.

### Dataset Overview using df.info()

The `df.info()` function provides a quick summary of the dataset structure. It shows the number of entries, column names, data types, and missing values.

This helps in understanding the dataset clearly before performing any cleaning or analysis.

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Statistical Summary using df.describe()

The `df.describe()` function provides statistical details of numerical columns such as mean, minimum, maximum, and quartile values.

This helps in understanding the distribution of data and identifying possible outliers before deeper analysis.

This step is important because it helps us understand the overall pattern of the data before performing analysis.

In [35]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Data Cleaning

Before analyzing the dataset, I checked for missing values and handled them carefully.

- The Age column had 177 missing values, so I filled them using the median since it is more stable for numerical data.
- The Cabin column had too many missing values (687), so it was dropped because it would not provide useful information.
- The Embarked column had only 2 missing values, so I filled them using the mode (most frequent value).

This cleaning step ensures the dataset is complete and ready for analysis.

In [36]:
import pandas as pd

# Fill missing Age with median
df["Age"] = df["Age"].fillna(df["Age"].median())

# Fill missing Embarked with mode (safe version)
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode().iloc[0])

# Drop Cabin safely
if "Cabin" in df.columns:
    df = df.drop("Cabin", axis=1)

# Remove duplicates
df = df.drop_duplicates()

# Check missing values
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Data Analysis

I used groupby() to explore how different factors affected survival.

In [37]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [38]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [39]:
df.groupby("Pclass")["Age"].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

In [40]:
import pandas as pd
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 60, 100],
    labels=["Child", "Teen", "Adult", "Senior"]
)
# Survival rate by age group
df.groupby("Age_Group", observed=False)["Survived"].mean()

Age_Group
Child     0.579710
Teen      0.428571
Adult     0.365753
Senior    0.227273
Name: Survived, dtype: float64

### Filtering Data

I filtered specific groups to better understand survival patterns.

In [41]:
df[(df["Sex"] == "female") & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Group
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C,Adult
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,Teen
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult

In [42]:
df[(df["Age"] < 12) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Group
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,Child
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,C,Child
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,S,Child
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,Child
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,Child
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,S,Child
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,Child
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,S,Child
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,Child
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,S,Child
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,S,Child
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,Child
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,Child
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,Child
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,Child
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,C,Child
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,Child
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,Child
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,C,Child
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,C,Child
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,S,Child
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,Child
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,S,Child
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,S,Child
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,Child
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,S,Child
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,C,Child
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,C,Child
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,S,Child
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,S,Child
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,Child
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,Child
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,S,Child
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,Child
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,S,Child
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,Child
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,Child
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,Child
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,Child

In [43]:
df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_Group
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Adult
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Adult
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Adult

### Key Insights

- From the analysis, it is clear that females had a much higher survival rate compared to males.

- Passenger class also had a strong impact. People in 1st class were more likely to survive than those in lower classes.

- Children seem to have a relatively higher survival rate, suggesting they may have been given priority.

- The highest survival rate was observed among female passengers in 1st class, especially those who were younger.